### ISSUE TITLE
neo rasterize buffer

### ISSUE THREAD

**Issue by ocourtin** [datapink/Neat-EO.pink#6]
add a `--buffer` option to allow natively, to deal with point and linestring geometries  
and perform buffer and negative buffer on (multi)polygons

**Comment by ocourtin** [comment]
Without:
![Screenshot from 2020-02-06 22-42-52](https://user-images.githubusercontent.com/1718264/73981263-2b304e80-4932-11ea-9066-eb83e6b36bc3.png)

With negative buffer: 
![Screenshot from 2020-02-06 22-42-19](https://user-images.githubusercontent.com/1718264/73981267-2d92a880-4932-11ea-9b54-e2b8dc35fbe8.png)

**Comment by baristahell** [comment]
Hello! Thanks for NEO... 

.. But I'm trying to generate a new cover for a geojson, which worked well the whole week, except today.. I think I found out what was happening, this functionality caused  https://github.com/datapink/neat-EO/blob/master/neat_eo/geojson.py#L13 to not be usable by https://github.com/datapink/neat-EO/blob/master/neat_eo/tools/cover.py#L100 anymore. 

Thanks :)
