### ISSUE TITLE
How can we start training on top of saved model in Neat-EO?

### ISSUE THREAD

**Issue by sulabh9999** [datapink/Neat-EO.pink#7]
I have existing saved checkpoint-00005.pth and want to retrain on top of it, also tried but it's creating checkpoint-00001 to 5 again. In our case we have list of large images(1-2 GB) so we decided to save model for next iteration of training.

**Comment by ocourtin** [comment]
```--resume --checkpoint path_to/ checkpoint-00005.pth  --epochs N```
With N > 5   

Cf doc ```neo train -h```

**Comment by sulabh9999** [comment]
Thanks @ocourtin
