### ISSUE TITLE
TernausNetV2: Fully Convolutional Network for Instance Segmentation

### ISSUE THREAD

**Issue by oneOfThePeople** [datapink/Neat-EO.pink#8]
hi,
i just want to ask where this part implement in your code
thank you for all

**Comment by ocourtin** [comment]
From this paper (TernausNetv2), two notions were took, to enhance Unet:
- Use a ResNet like encoder
- Copy encoder layer to Decoder ones  (to mimic residual notion)

Cf https://github.com/datapink/Neat-EO.pink/blob/master/neat_eo/nn/albunet.py

If you have a better paper to cite to for theses two notions, let me know.
